# Generated by Django 4.2 on 2025-01-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_alumno_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='students',
        ),
    ]
